### ISSUE TITLE
relation_name is empty and stops Github Actions

### ISSUE THREAD

**Issue by hugohahn009** [rfdearborn/dbt-docs-to-notion#16]
Hello @rfdearborn,

first of all, thank you for building this tool, it's really great. I am trying to implement it in my company to promote self service w/ dbt 🌞 
---
I went through the whole setup and successfully imported the first documented models in a Notion DB.
However, at some points, Github Actions fails because of a specific model documentation (and I do not know which).

Here is the error:

`
Traceback (most recent call last):
  File "/home/runner/work/_actions/rfdearborn/dbt-docs-to-notion/v1.0.9/dbt_docs_to_notion.py", line 513, in <module>
    main()
  File "/home/runner/work/_actions/rfdearborn/dbt-docs-to-notion/v1.0.9/dbt_docs_to_notion.py", line 413, in main
    "content": data['relation_name'][:2000]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
`

My guess is that some model does not have a 'relation_name'. Could you help me on this topic ? Thank you !

**Comment by hugohahn009** [comment]
I was able to find the culprit. One of our data models was materialised as "[ephemeral](https://docs.getdbt.com/docs/build/materializations#ephemeral)" and had not relation_name. It was causing the bug.
